CREATE TABLE users(
userid VARCHAR(20) NOT NULL,
accessible_money INT UNSIGNED NOT NULL DEFAULT 0,
reserved_money INT UNSIGNED NOT NULL DEFAULT 0,
PRIMARY KEY(userid)
);

CREATE TABLE user_stocks(
   userid VARCHAR(20) NOT NULL,
   stock_name VARCHAR(3) NOT NULL,
   accessible_stocks INT UNSIGNED NOT NULL DEFAULT 0,
   reserved_stocks INT UNSIGNED NOT NULL DEFAULT 0,
   buy_trigger INT UNSIGNED,
   buy_amount INT UNSIGNED,
   sell_trigger INT UNSIGNED,
   sell_amount INT UNSIGNED,
   bt_t_num BIGINT(15) UNSIGNED,
   st_t_num BIGINT(15) UNSIGNED,
   PRIMARY KEY(userid, stock_name),
   FOREIGN KEY(userid) REFERENCES users(userid)
   ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE pending_buys(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	userid VARCHAR(20) NOT NULL,
	stock_name VARCHAR(3) NOT NULL,
	expiry BIGINT(15) UNSIGNED NOT NULL,
	num INT(15) UNSIGNED NOT NULL,
	req_amount INT(15) UNSIGNED NOT NULL,
	stock_price INT(15) UNSIGNED NOT NULL,
	t_num INT(15) UNSIGNED NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(userid) REFERENCES users(userid)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE pending_sells(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT,
	userid VARCHAR(20) NOT NULL,
	stock_name VARCHAR(3) NOT NULL,
	stock_price INT(15) UNSIGNED NOT NULL,
	expiry BIGINT(15) UNSIGNED NOT NULL,
	num INT(15) UNSIGNED NOT NULL,
	req_amount INT(15) UNSIGNED NOT NULL,
	t_num INT(15) UNSIGNED NOT NULL,
	PRIMARY KEY(id),
	FOREIGN KEY(userid) REFERENCES users(userid)
	ON DELETE CASCADE ON UPDATE CASCADE
);